// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.3
// 	protoc        v5.29.3
// source: internal/testpb/test.proto

package testpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TestItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         int32                  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestItem) Reset() {
	*x = TestItem{}
	mi := &file_internal_testpb_test_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestItem) ProtoMessage() {}

func (x *TestItem) ProtoReflect() protoreflect.Message {
	mi := &file_internal_testpb_test_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestItem.ProtoReflect.Descriptor instead.
func (*TestItem) Descriptor() ([]byte, []int) {
	return file_internal_testpb_test_proto_rawDescGZIP(), []int{0}
}

func (x *TestItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TestItem) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type TestUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Age           int32                  `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestUser) Reset() {
	*x = TestUser{}
	mi := &file_internal_testpb_test_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestUser) ProtoMessage() {}

func (x *TestUser) ProtoReflect() protoreflect.Message {
	mi := &file_internal_testpb_test_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestUser.ProtoReflect.Descriptor instead.
func (*TestUser) Descriptor() ([]byte, []int) {
	return file_internal_testpb_test_proto_rawDescGZIP(), []int{1}
}

func (x *TestUser) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TestUser) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *TestUser) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

var File_internal_testpb_test_proto protoreflect.FileDescriptor

var file_internal_testpb_test_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x70,
	0x62, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x74, 0x65,
	0x73, 0x74, 0x70, 0x62, 0x22, 0x34, 0x0a, 0x08, 0x54, 0x65, 0x73, 0x74, 0x49, 0x74, 0x65, 0x6d,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x46, 0x0a, 0x08, 0x54, 0x65,
	0x73, 0x74, 0x55, 0x73, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d,
	0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c,
	0x12, 0x10, 0x0a, 0x03, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x61,
	0x67, 0x65, 0x42, 0x28, 0x5a, 0x26, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x67, 0x65, 0x72, 0x6d, 0x74, 0x62, 0x2f, 0x73, 0x69, 0x64, 0x62, 0x2f, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_testpb_test_proto_rawDescOnce sync.Once
	file_internal_testpb_test_proto_rawDescData = file_internal_testpb_test_proto_rawDesc
)

func file_internal_testpb_test_proto_rawDescGZIP() []byte {
	file_internal_testpb_test_proto_rawDescOnce.Do(func() {
		file_internal_testpb_test_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_testpb_test_proto_rawDescData)
	})
	return file_internal_testpb_test_proto_rawDescData
}

var file_internal_testpb_test_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_testpb_test_proto_goTypes = []any{
	(*TestItem)(nil), // 0: testpb.TestItem
	(*TestUser)(nil), // 1: testpb.TestUser
}
var file_internal_testpb_test_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_testpb_test_proto_init() }
func file_internal_testpb_test_proto_init() {
	if File_internal_testpb_test_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_testpb_test_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_testpb_test_proto_goTypes,
		DependencyIndexes: file_internal_testpb_test_proto_depIdxs,
		MessageInfos:      file_internal_testpb_test_proto_msgTypes,
	}.Build()
	File_internal_testpb_test_proto = out.File
	file_internal_testpb_test_proto_rawDesc = nil
	file_internal_testpb_test_proto_goTypes = nil
	file_internal_testpb_test_proto_depIdxs = nil
}
